apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: error-rate
    interval: 10s
    failureCondition: result >= 10
    failureLimit: 2
    provider:
      web:
        url: http://{{ args.service-name }}/health
        jsonPath: "{$.error-rate}"
