apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-world
spec:
  replicas: 5
  strategy:
    canary:
      analysis:
        templates:
        - templateName: error-rate
        - templateName: latency
        startingStep: 1
        args:
        - name: service-name
          value: metrics-sample.default.svc.cluster.local
      steps:
      - setWeight: 10
      - pause: {duration: 20}
      - setWeight: 50
      - pause: {duration: 40}
      - setWeight: 70
      - pause: {duration: 60}
      - setWeight: 100
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: us-central1-docker.pkg.dev/sadaindia-tvm-poc-de/demo-repo/helloworld:v2
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
